In [4]:
#WORKSHEET - 0

import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [5]:
#4.1 Exercise on Functions:

#TASK 1 – Unit Converter Program

def unit_converter():
    """
    Converts between different units of measurement.

    Conversion Types:
    1. Length (meters ↔ feet)
    2. Weight (kg ↔ lbs)
    3. Volume (liters ↔ gallons)

    Returns:
        float: Converted value
    """

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter choice (1/2/3): ")

    try:
        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("a. meters to feet")
            print("b. feet to meters")
            sub = input("Choose option (a/b): ")

            if sub == "a":
                result = value * 3.28084
                print(f"{value} meters = {result} feet")
                return result
            elif sub == "b":
                result = value / 3.28084
                print(f"{value} feet = {result} meters")
                return result

        elif choice == "2":
            print("a. kg to lbs")
            print("b. lbs to kg")
            sub = input("Choose option (a/b): ")

            if sub == "a":
                result = value * 2.20462
                print(f"{value} kg = {result} lbs")
                return result
            elif sub == "b":
                result = value / 2.20462
                print(f"{value} lbs = {result} kg")
                return result

        elif choice == "3":
            print("a. liters to gallons")
            print("b. gallons to liters")
            sub = input("Choose option (a/b): ")

            if sub == "a":
                result = value * 0.264172
                print(f"{value} liters = {result} gallons")
                return result
            elif sub == "b":
                result = value / 0.264172
                print(f"{value} gallons = {result} liters")
                return result

        else:
            print("Invalid conversion type.")
            return None

    except ValueError:
        print("Invalid input! Please enter numeric value.")
        return None


# Calling the function
unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 2
Enter value to convert: 213
a. kg to lbs
b. lbs to kg
Choose option (a/b): 1


In [6]:
#Task 2: Mathematical Operations on List

def sum_numbers(numbers):
    """
    Returns the sum of a list of numbers.
    """
    return sum(numbers)


def average_numbers(numbers):
    """
    Returns the average of a list of numbers.
    """
    return sum(numbers) / len(numbers)


def max_number(numbers):
    """
    Returns the maximum value from a list.
    """
    return max(numbers)


def min_number(numbers):
    """
    Returns the minimum value from a list.
    """
    return min(numbers)


def math_operations():
    """
    Performs selected mathematical operation on user-provided list.
    """

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice (1/2/3/4): ")

    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if len(numbers) == 0:
            print("Empty list not allowed.")
            return

        if choice == "1":
            print("Sum:", sum_numbers(numbers))
        elif choice == "2":
            print("Average:", average_numbers(numbers))
        elif choice == "3":
            print("Maximum:", max_number(numbers))
        elif choice == "4":
            print("Minimum:", min_number(numbers))
        else:
            print("Invalid operation choice.")

    except ValueError:
        print("Invalid input! Please enter numbers only.")


# Call the function
math_operations()

Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1/2/3/4): 1
Enter numbers separated by spaces: 3 2 1 4
Sum: 10.0


In [7]:
#4.2 Exercise on List Manipulation:

# 1️ - Extract Every Other Element

def extract_every_other(lst):
    """
    Returns every other element from the list,
    starting from the first element.

    Parameters:
        lst (list): Input list

    Returns:
        list: New list containing every second element
    """
    return lst[::2]


# Example
print("1.", extract_every_other([1, 2, 3, 4, 5, 6]))

1. [1, 3, 5]


In [8]:
# 2️ - Slice a Sublist

def get_sublist(lst, start, end):
    """
    Returns a sublist from index 'start' to 'end' (inclusive).

    Parameters:
        lst (list): Input list
        start (int): Starting index
        end (int): Ending index (inclusive)

    Returns:
        list: Sublist from start to end
    """
    return lst[start:end+1]


# Example
print("2.", get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

2. [3, 4, 5]


In [9]:
# 3️ - Reverse a List Using Slicing

def reverse_list(lst):
    """
    Returns the reversed version of the input list using slicing.

    Parameters:
        lst (list): Input list

    Returns:
        list: Reversed list
    """
    return lst[::-1]


# Example
print("3.", reverse_list([1, 2, 3, 4, 5]))

3. [5, 4, 3, 2, 1]


In [10]:
# 4️ - Remove the First and Last Elements

def remove_first_last(lst):
    """
    Removes the first and last elements from the list.

    Parameters:
        lst (list): Input list

    Returns:
        list: List without first and last elements
    """
    return lst[1:-1]


# Example
print("4.", remove_first_last([1, 2, 3, 4, 5]))

4. [2, 3, 4]


In [11]:
# 5️ - Get the First n Elements

def get_first_n(lst, n):
    """
    Returns the first n elements of the list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to extract

    Returns:
        list: First n elements
    """
    return lst[:n]


# Example
print("5.", get_first_n([1, 2, 3, 4, 5], 3))

5. [1, 2, 3]


In [12]:
# 6 -  Extract the Last n Elements

def get_last_n(lst, n):
    """
    Returns the last n elements of the list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to extract

    Returns:
        list: Last n elements
    """
    return lst[-n:]


# Example
print("6.", get_last_n([1, 2, 3, 4, 5], 2))

6. [4, 5]


In [13]:
# 7️ - Extract Elements in Reverse Order (Skip One)

def reverse_skip(lst):
    """
    Returns every second element starting from
    the second-to-last element, moving backward.

    Parameters:
        lst (list): Input list

    Returns:
        list: New list of reversed skipped elements
    """
    return lst[-2::-2]


# Example
print("7.", reverse_skip([1, 2, 3, 4, 5, 6]))

7. [5, 3, 1]


In [14]:
# 4.3 Exercise on Nested List
# 1️ - Flatten a Nested List

def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): Nested list

    Returns:
        list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result


# Example
print("1.", flatten([[1, 2], [3, 4], [5]]))

1. [1, 2, 3, 4, 5]


In [15]:
# 2 - Accessing Nested List Elements

def access_nested_element(lst, indices):
    """
    Accesses an element in a nested list using a list of indices.

    Parameters:
        lst (list): Nested list
        indices (list): List of indices

    Returns:
        element at specified position
    """
    element = lst
    for index in indices:
        element = element[index]
    return element


# Example
lst_example = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("2.", access_nested_element(lst_example, [1, 2]))

2. 6


In [16]:
# 3️ - Sum of All Elements in a Nested List

def sum_nested(lst):
    """
    Returns the sum of all numeric elements
    in a nested list (any depth).
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# Example
print("3.", sum_nested([[1, 2], [3, [4, 5]], 6]))

3. 21


In [17]:
# 4️ - Remove Specific Element from a Nested List

def remove_element(lst, elem):
    """
    Removes all occurrences of elem
    from a nested list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


# Example
print("4.", remove_element([[1, 2], [3, 2], [4, 5]], 2))

4. [[1], [3], [4, 5]]


In [18]:
# 5️ - Find the Maximum Element in a Nested List

def find_max(lst):
    """
    Returns the maximum element
    in a nested list.
    """
    flat_list = flatten(lst)
    return max(flat_list)


# Example
print("5.", find_max([[1, 2], [3, [4, 5]], 6]))

5. 6


In [19]:
# 6️ - Count Occurrences of an Element

def count_occurrences(lst, elem):
    """
    Counts how many times elem appears
    in a nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# Example
print("6.", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

6. 3


In [20]:
# 7️ - Deep Flatten (List of Lists of Lists)

def deep_flatten(lst):
    """
    Flattens a deeply nested list
    into a single list.
    """
    return flatten(lst)


# Example
print("7.", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

7. [1, 2, 3, 4, 5, 6, 7, 8]


In [21]:
# 8️ - Nested List Average

def average_nested(lst):
    """
    Calculates the average of all elements
    in a nested list.
    """
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)


# Example
print("8.", average_nested([[1, 2], [3, 4], [5, 6]]))

8. 3.5


In [22]:
#10 To - Do - NumPy

In [23]:
#10.1 Basic Vector and Matrix Operation with Numpy.
#Problem - 1: Array Creation:

import numpy as np

#1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("1. Empty 2x2 Array:")
print(empty_array)


#2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("\n2. All Ones 4x2 Array:")
print(ones_array)


#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full_array = np.full((3, 3), 7)  # 3x3 array filled with 7
print("\n3. Array Filled with 7:")
print(full_array)


#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
given_array = np.array([[1, 2], [3, 4]])

zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros Like Given Array:")
print(zeros_like_array)


#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_like_array = np.ones_like(given_array)
print("\n5. Ones Like Given Array:")
print(ones_like_array)


#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4]

numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array:")
print(numpy_array)

1. Empty 2x2 Array:
[[3.4283183e-315 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]

2. All Ones 4x2 Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array Filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Given Array:
[[0 0]
 [0 0]]

5. Ones Like Given Array:
[[1 1]
 [1 1]]

6. Converted NumPy Array:
[1 2 3 4]


In [24]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array_range = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(array_range)


#2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix from 0 to 8:")
print(matrix_3x3)


#3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(identity_matrix)


#4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)
mean_value = random_array.mean()

print("\n4. Random Array of Size 30:")
print(random_array)
print("Mean of the array:", mean_value)


#5. Create a 10X10 array with random values and find the minimum and maximum values.
random_matrix = np.random.random((10, 10))

min_value = random_matrix.min()
max_value = random_matrix.max()

print("\n5. 10x10 Random Matrix:")
print(random_matrix)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


#6. Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1   # 5th element (index starts from 0)

print("\n6. Zero Array with 5th Element Replaced:")
print(zero_array)


#7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print("\n7. Reversed Array:")
print(reversed_arr)


#8. Create a 2d array with 1 on border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0

print("\n8. 2D Array with Border 1 and Inside 0:")
print(border_array)


#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8))

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("\n9. 8x8 Checkerboard Pattern:")
print(checkerboard)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array of Size 30:
[0.77766469 0.97636184 0.89582994 0.5749431  0.86416052 0.11163588
 0.01692558 0.53208291 0.97610163 0.04804706 0.22929199 0.26423109
 0.56808205 0.20789861 0.13057831 0.54654238 0.66919579 0.70339572
 0.75925508 0.1993044  0.34110905 0.75816474 0.22623645 0.98945541
 0.56969692 0.38442786 0.84959018 0.04223699 0.25921733 0.77195981]
Mean of the array: 0.5081207766735955

5. 10x10 Random Matrix:
[[0.32765173 0.56988782 0.52242766 0.18498941 0.20806504 0.91594564
  0.07486798 0.9939688  0.68696701 0.59314017]
 [0.25501134 0.80823108 0.78623612 0.32263895 0.74712236 0.78814772
  0.98213472 0.39535767 0.00179077 0.30631353]
 [0.20116156 0.52780658 0.1563402  0.64340453 0.15075377 0.68768792
  0.35645

In [25]:
# Problem 3: Array Operations

import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#1. Add the two array.
add_xy = x + y
print("1. Addition of x and y:")
print(add_xy)


#2. Subtract the two array.
sub_xy = x - y
print("\n2. Subtraction of x and y:")
print(sub_xy)


#3. Multiply the array with any integers of your choice.
mul_x = x * 3
mul_y = y * 2

print("\n3. Multiplication of x by 3:")
print(mul_x)
print("\nMultiplication of y by 2:")
print(mul_y)


#4. Find the square of each element of the array.
square_x = x ** 2
square_y = y ** 2

print("\n4. Square of x:")
print(square_x)
print("\nSquare of y:")
print(square_y)



#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot Product v · w:")
print(dot_vw)
print("\nDot Product x · v:")
print(dot_xv)
print("\nDot Product x · y:")
print(dot_xy)


#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.
#(a) Concatenate x and y along rows
concat_rows = np.concatenate((x, y), axis=0)
print("\n6a. Concatenate x and y along rows:")
print(concat_rows)


#(b) Concatenate v and w along columns
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_columns = np.concatenate((v_col, w_col), axis=1)

print("\n6b. Concatenate v and w along columns:")
print(concat_columns)


#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v))
    print("\n7. Concatenate x and v:")
    print(concat_xv)
except ValueError as e:
    print("\n7. Error occurred while concatenating x and v:")
    print(e)


#x is a 2D array with shape (2,2)
#v is a 1D array with shape (2,)
#NumPy cannot concatenate arrays of different dimensions directly.
#Therefore, a dimension mismatch error occurs.
#If needed, we could reshape v to match dimensions before concatenation.

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x by 3:
[[ 3  6]
 [ 9 15]]

Multiplication of y by 2:
[[10 12]
 [14 16]]

4. Square of x:
[[ 1  4]
 [ 9 25]]

Square of y:
[[25 36]
 [49 64]]

5. Dot Product v · w:
219

Dot Product x · v:
[29 77]

Dot Product x · y:
[[19 22]
 [50 58]]

6a. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b. Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Error occurred while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [26]:
#Problem - 4: Matrix Operations:

#Given Matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)


#Prove A · A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_result = np.dot(A, A_inv)

print("\nA Inverse:\n", A_inv)
print("\nA · A⁻¹:\n", identity_result)


#Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nA · B:\n", AB)
print("\nB · A:\n", BA)



#Prove (AB)ᵀ = Bᵀ Aᵀ
AB_transpose = AB.T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T:\n", AB_transpose)
print("\nB^T · A^T:\n", BT_AT)


Matrix A:
 [[3 4]
 [7 8]]

Matrix B:
 [[5 3]
 [2 1]]

A Inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A · A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A · B:
 [[23 13]
 [51 29]]

B · A:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T · A^T:
 [[23 51]
 [13 29]]


In [27]:
#Step 1: Represent in Matrix Form AX = B

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

B_sys = np.array([-1, -3, 9])

print("Matrix A:\n", A_sys)
print("\nMatrix B:\n", B_sys)


#Step 2: Solve using Inverse Method

A_sys_inv = np.linalg.inv(A_sys)
X = np.dot(A_sys_inv, B_sys)

print("\nSolution using Inverse Method:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


#Using np.linalg.inv (Directly)
X_direct = np.linalg.inv(A_sys).dot(B_sys)

print("\nSolution using np.linalg.inv():")
print(X_direct)

Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Matrix B:
 [-1 -3  9]

Solution using Inverse Method:
x = 2.0
y = 1.0
z = -2.0

Solution using np.linalg.inv():
[ 2.  1. -2.]


In [28]:
# 10.2 Experiment: How Fast is NumPy?

import numpy as np
import time

#1. Element-wise Addition:

#Using Python Lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print("Python List Addition Time:", end_time - start_time, "seconds")


#Using NumPy Arrays
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array_add = array1 + array2
end_time = time.time()
print("NumPy Array Addition Time:", end_time - start_time, "seconds")



#2. Element-wise Multiplication
#Using Python Lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print("Python List Multiplication Time:", end_time - start_time, "seconds")


#Using NumPy Arrays
start_time = time.time()
result_array_mul = array1 * array2
end_time = time.time()
print("NumPy Array Multiplication Time:", end_time - start_time, "seconds")


Python List Addition Time: 0.1058053970336914 seconds
NumPy Array Addition Time: 0.0035495758056640625 seconds
Python List Multiplication Time: 0.10745477676391602 seconds
NumPy Array Multiplication Time: 0.004337787628173828 seconds


In [29]:
#3. Dot Product
#Using Python Lists
start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()

print("Python List Dot Product Time:", end_time - start_time, "seconds")


#Using NumPy Arrays
start_time = time.time()
dot_array = np.dot(array1, array2)
end_time = time.time()

print("NumPy Dot Product Time:", end_time - start_time, "seconds")


#4. Matrix Multiplication
#Using Python Lists
# Create 1000x1000 matrices as lists
size = 1000
matrix1 = [[1 for _ in range(size)] for _ in range(size)]
matrix2 = [[1 for _ in range(size)] for _ in range(size)]

start_time = time.time()
# Manual matrix multiplication
result_matrix = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
end_time = time.time()
print("Python List Matrix Multiplication Time:", end_time - start_time, "seconds")


#Using NumPy Arrays
matrix1_np = np.ones((size, size))
matrix2_np = np.ones((size, size))

start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()

print("NumPy Matrix Multiplication Time:", end_time - start_time, "seconds")

Python List Dot Product Time: 0.10703873634338379 seconds
NumPy Dot Product Time: 0.0017518997192382812 seconds
Python List Matrix Multiplication Time: 299.99845123291016 seconds
NumPy Matrix Multiplication Time: 0.06195425987243652 seconds
